version: "3.8"

services:
  db:
    image: mongo:latest # Use o último versão do mongo.  Certifique-se que este é a versão que você está usando.
    ports:
      - "27017:27017" # Expor a porta 27017 (porta padrão do MongoDB) para o host
    volumes:
      - mongodb_data:/data/db # Alocar um volume para o banco de dados
    environment:
      - MongoDB_URI=mongodb://localhost:27017/meu_banco_de_dados # Definir o URI do MongoDB
      - MongoDB_PASSWORD=sua_senha # Substitua por sua senha (se você estiver usando autenticação)
      - MongoDB_USER=meu_usuario # Substitua por seu usuário MongoDB
      - MongoDB_DATABASE=meu_banco # Substitua por o nome do seu banco
